### ISSUE TITLE
Files have duplicate values

### ISSUE THREAD

**Issue by apigban** [apigban/SMP_scraper#3]
``Traceback (most recent call last):
  File "/home/apigban/.local/share/virtualenvs/PycharmProjects-T4r1JFI1/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/apigban/.local/share/virtualenvs/PycharmProjects-T4r1JFI1/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: duplicate key value violates unique constraint "stock_pkey"
**DETAIL:  Key (stock_id)=(AUB2016-08-01) already exists.**
...
...
``
![selection_108](https://user-images.githubusercontent.com/2720851/47408640-c7acfc80-d792-11e8-8a8e-e706f2212c3e.png)

**Comment by apigban** [comment]
Fixed. Duplicates are now handled by db_func.db_commit_stock() below:


``    if session.query(Stock).filter(Stock.stock_id == stock_id).first() is None:
        unique_db_entry = Stock(stock_id, symbol, trade_date, price_open, price_high, price_low, price_close, volume)

        session.add(unique_db_entry)
        session.commit()
        db_logger.info(f'Commit Done. Stock: {unique_db_entry.symbol}    Trade date:  {unique_db_entry.trade_date} ')
        session.close()
return unique_db_entry``

![selection_109](https://user-images.githubusercontent.com/2720851/47408639-c7acfc80-d792-11e8-8990-456678598967.png)
